# Generated by Django 5.2.7 on 2025-10-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='D0010', max_length=10)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='IMPORTED', max_length=20)),
                ('sequence_number', models.CharField(blank=True, max_length=20)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('record_type', models.CharField(blank=True, max_length=1)),
                ('sender', models.CharField(blank=True, max_length=10)),
                ('receiver', models.CharField(blank=True, max_length=10)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('meter_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Direct Debit'), ('P', 'Prepayment')], max_length=1)),
                ('flow_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter_readings.flowfile')),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='meter_readings.meterpoint')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=10)),
                ('reading_date', models.DateTimeField()),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reading_type', models.CharField(default='N', max_length=1)),
                ('measurement_method', models.CharField(default='T', max_length=1)),
                ('flow_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter_readings.flowfile')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter_readings.meter')),
            ],
            options={
                'ordering': ['reading_date'],
            },
        ),
    ]
