# Generated by Django 5.2.7 on 2025-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowfile',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of file contents for idempotency', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='flowfile',
            index=models.Index(fields=['filename'], name='meter_readi_filenam_33fe35_idx'),
        ),
        migrations.AddIndex(
            model_name='flowfile',
            index=models.Index(fields=['checksum'], name='meter_readi_checksu_71a5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['serial_number'], name='meter_readi_serial__f7b57a_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['meter_point'], name='meter_readi_meter_p_1a1bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='meterpoint',
            index=models.Index(fields=['mpan'], name='meter_readi_mpan_657281_idx'),
        ),
        migrations.AddIndex(
            model_name='registerreading',
            index=models.Index(fields=['meter', 'register_id'], name='meter_readi_meter_i_02292e_idx'),
        ),
        migrations.AddIndex(
            model_name='registerreading',
            index=models.Index(fields=['reading_date'], name='meter_readi_reading_adde83_idx'),
        ),
        migrations.AddConstraint(
            model_name='registerreading',
            constraint=models.UniqueConstraint(fields=('meter', 'register_id', 'reading_date', 'reading_value'), name='uniq_reading_natural_key'),
        ),
    ]
