# Generated by Django 5.2.7 on 2025-10-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0002_flowfile_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='mpan',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
