# Generated by Django 5.2.7 on 2025-10-07 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0003_alter_meter_serial_number_alter_meterpoint_mpan'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='mpan',
            field=models.CharField(db_index=True, default='0000000000000', help_text='Meter Point Administration Number', max_length=20),
        ),
        migrations.AddField(
            model_name='meter',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
