# Generated by Django 5.2.7 on 2025-10-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0004_add_mpan_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='meter_point',
        ),
        migrations.DeleteModel(
            name='MeterPoint',
        ),
    ]
